[package]
name = "cversion"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
floatrun = { path = "../floatrun" }

[build-dependencies]
cc = "1.0"
